### ISSUE TITLE
Loading a program from the duplicator doesn't clear the manager first

### ISSUE THREAD

**Issue by Rodg88** [hilburn/StevesAddons#45]
Possibly intended, but like the title says, using a manager duplicator to load a saved program doesn't clear the manager before pasting the new program in. So loading a program from a manager into a duplicator, then using that duplicator on the same manager again ends up with two of every command, in the same locations as the originals too, so it's hard to notice.

**Comment by hilburn** [comment]
yup - this is intended behaviour from before there was a copy button - this allowed you to copy and paste the entire manager back into itself.

I will have a look at how I could make it clear the manager without changing the current behaviour - otherwise I'd need a bit more of a show of support before changing the mechanic as it is, so I'll leave this open

**Comment by jameseck** [comment]
If my opinion counts for anything and its a choice between one or the
other, I'd prefer that it overwrote the target manager rather than merging
the commands :)

Is it possible to have different options on the duplicator, maybe with
shift-mousewheel to change the mode between merge and overwrite or
something similar.

**Comment by hilburn** [comment]
Like I said - I'll look into it

**Comment by hilburn** [comment]
Added in 0.10.3
